<?php
include_once 'classes/paginas.class.php';
include_once 'classes/greservas.class.php';
include_once 'assets/funciones.php';


/* $BASEPATH = "http://localhost/rental2/calendar/";
 define("BASEPATH", $BASEPATH);
 */

/* $configFile = "rental2/calendar/includes/config.inc.php";
  $synctzFile = "rental2/calendar/includes/synctz.inc.php";
  if (file_exists($configFile)) {
      require_once ($configFile);
	  require_once ($synctzFile);
  } else {
	  exit;
  }

  require_once ("rental2/calendar/classes/class.db.php");

  require_once ("rental2/calendar/classes/class.vault.php");
  Vault::set('Database', new Database(DB_SERVER, DB_USER, DB_PASS, DB_DATABASE));
  $db = Vault::get("Database");
  $db->connect();
*/

//$XACTUAL=$_GET['ruta'];
?>
<head>
  <meta charset="UTF-8">
  <title>Buscar Checkout</title>
     <link rel="stylesheet" href="assets/css/reservas2.css">
     <link href="https://fonts.googleapis.com/css?family=Didact+Gothic&display=swap" rel="stylesheet">
     
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

  <script>
  $( function() {
    $( "#datep1" ).datepicker();
  } );

   $( function() {
    $( "#datep2" ).datepicker();
  } );

  </script>

     
     
</head>


<body>

<?php


$XOBJPAG=new paginas;
$XPAGINA="'PAG_RES_GESTION'";
$XLENG="'ESP'";
$XCLASS="'001'";
$XRSPAG=$XOBJPAG->FncBuscarPagina($XLENG, $XPAGINA, $XCLASS);
$XI=0;
while($XROWPAG=$XOBJPAG->obtener_fila($XRSPAG)){//CREA EL ARREGLO PARA EL MENU
	$XLABEL[$XI]=utf8_encode($XROWPAG[0]);
	$XDISP[$XI]=$XROWPAG[1];
	$XAUT[$XI]=$XROWPAG[2];
	$XURL[$XI]=$XROWPAG[3];
	$XI++;
}
?>
<script type="text/javascript" src="assets/js/gestion_reservas3.js" ></script>
<script src="https://codepen.io/shshaw/pen/QmZYMG.js"></script>
<!-- <input type="radio" name="cice" id="nav-1" checked> -->
<div id="app">
<!-- Generated by IcoMoon.io -->
 <header>
   <nav>
    <div class="logo">
       <a href="index2.php"><img src="assets/images/logo-horos-transparente.fw.png" alt=""></a>
    </div>
    
      <div class="menu-a">
          <a href="buscar_reservas.php">Retornar</a>
      <a href="index2.php">Menu Principal</a>
      <a href="home.php">Disponibilidad de Habitaciones</a>
       </div>


    </nav>
  </header>
  <div class="ui-pages">
    <article id="buscar">
           	<?php
// Se buscan reservas creadas
             $fecha_actual = date("Y-m-d");
             $fecha_inicial = date("Y-m-d",strtotime($fecha_actual."- 4 month"));
             $fecha_final = date("Y-m-d",strtotime($fecha_actual."+ 4 month"));
        	echo'
            <form class="buscar" action="buscar_abonos1.php" method="post">
                <h1>BUSCAR ABONOS </h1>
                <div class="buscar-reserva">
                    <div class="rango">
                    <div><label> Numero de Checkin</label>
               	  		<input type="text" id="TxtReserva" name="idres" placeholder="'.$XLABEL[2].'" />
                    </div>
                    <div><label>Nombre del Cliente</label>
                        <input type="text" id="Txtnombre" name="guest" placeholder="'.$XLABEL[3].'" />
                    </div>
                     <div><label>Numero Habitacion</label>
                        <input type="text" id="numhab" name="numhab" placeholder="'.$XLABEL[4].'" />
                    </div>
                </div>';
                  $calnav = '';
                  $calnav = $calnav. '
                <div class="rango">
                    <div>
                        <label> Desde</label>
                        <input type="text" name="fechadesde" id="datep1" step="1" value='.$fecha_inicial .'>
                    </div>
                    <div> '.
                        ' <label>Hasta</label>
                        <input type="text" name="fechahasta" id="datep2" step="1" value='. $fecha_final .'>
                    </div>
                     <div  class="botones">
                        <input type="submit"  name="buscar" id="BtnBuscar" value="'.$XLABEL[4].'" />
                     </div>

                </div> 

                </div>
               	   </div>
                </div>
			
            </form>';
            echo $calnav;
			?>
		
<a href=""></a>
          	<div id="buscar">
          	    <table id="resultado" >
          	<?php
          	
          	if ( isset($_POST['buscar']))
          	{
             $idhab = "";
          	 $idres=$_POST['idres'];
          	$guest= $_POST['guest'];
             if (isset($fecha)) {
              if ($fecha==1)
          	  {
               $fecha_actual = date("Y-m-d");
               $fechadesde = date("Y-m-d",strtotime($fecha_actual."- 4 month"));
               $fechahasta = date("Y-m-d",strtotime($fecha_actual."+ 4 month"));
          	  }
            }
          	else
          	{
          	$postdesde = $_POST['fechadesde'];
            $posthasta = $_POST['fechahasta'];
          	$fechadesde= date("Y-m-d", strtotime($postdesde));
          	$fechahasta= date("Y-m-d",strtotime($posthasta));
          	}
          	if (isset($_POST['numhab']))
          	    $numhab = $_POST['numhab'];
           }
           else
           {
             $numhab = "";
             $idres = "";
             $guest = "";
            $fecha_actual = date("Y-m-d");
             $fechadesde = date("Y-m-d",strtotime($fecha_actual."- 4 month"));
             $fechahasta= date("Y-m-d",strtotime($fecha_actual."+ 4 month"));
              $idstatus="%";
            }

           	$XOBJRES=new greservas;
           	$setid = "001";
           	$filtros = "zarest_sales.checkinid like '%".$idres."%' and zarest_sales.clientname like '%".$guest."%'
               and zarest_payements.date >= '".$fechadesde ."' and zarest_payements.date <= '".
              $fechahasta."' and zarest_sales.numhab like '%".$numhab."%'";

			$XRSRES=$XOBJRES->buscar_abonos1($filtros);
            $XNUMFILA = 0;
            	echo'<tr >
            	<td class="tituT" align="center" > Id pago </td>
                <td class="tituT" align="center" > # Checkin </td>
            	<td class="tituT" align="center" > Cliente </td>
                <td class="tituT" align="center" > Fecha Abono </td>
                <td class="tituT" align="center" > Valor Abono </td>
           	 	<td class="tituT" align="center" > Saldo </td>
   	 	 	 	<td class="tituT" align="center" > Numhab </td>
 	 	 	 	<td class="tituT" align="center" > Metodo de Pago </td>
               	<td class="tituT" align="center" > Modificar </td>
              	<td class="tituT" align="center" > Total Abonos </td>


             </tr>';

         //   $xi = $inicio;
         $totalabonos = 0;
         setlocale(LC_MONETARY, 'en_US');
            while($XROWRES=$XOBJRES->obtener_fila($XRSRES)){
         	    $numcheckin = $XROWRES[0];
				$fechaabono = $XROWRES[2];
				$nombre = $XROWRES[1];
               	$valor = (int)$XROWRES[3];
              	$saldo = $XROWRES[6];
              	$numhab = $XROWRES[5];
                $idpago = $XROWRES[7];
              	$metpago = $XROWRES[4];
              	$metodo = explode("~",$metpago);
       	       	$totalabonos = $totalabonos + $valor;

              	if ($metodo[0] == "0")
                  $metodopago = "Efectivo";
                else
                  $metodopago = "Tarjeta";
        		echo'<tr>
        		   <td > '.$idpago.'</td>
        	     	<td >' . $numcheckin.'</td>
        	    	<td > '.$nombre.'</td>
            	    <td >'.$fechaabono.'</td>
    	   	       	<td >'.$valor.'</td>
   	       	     	<td >'.$saldo.'</td>
                   	<td >'.$numhab.'</td>
                   	<td >'.$metodopago.'</td>';
                    echo '<td> <a class="checkin-img" onclick="Prcbuscarabono('.$idpago.')" style="cursor:pointer"><img src="assets/images/checkin.png" alt=""></a></td>
        	   	</td> ';
        	   	    echo '	<td >'.money_format('%(#10n',$totalabonos).'</td>';


    	   	    echo ' </tr> ';
               	$XNUMFILA++;
        	//   	$xi++;
              	}
                	echo'<tr>
        		   <td > TOTAL ABONOS: '.money_format('%(#10n',$totalabonos).'</td> </tr>';



// finaliza busqueda de reservas creadas
			?>
      	</table><img src="" alt="">

          	</div>

        
      </article>


  </div>
</div>

     <script  src="js/index.js"></script>
</body>
