<?php
include_once 'classes/paginas.class.php';
include_once 'classes/greservas.class.php';
include_once 'assets/funciones.php';


/* $BASEPATH = "http://localhost/rental2/calendar/";
 define("BASEPATH", $BASEPATH);
 */

/* $configFile = "rental2/calendar/includes/config.inc.php";
  $synctzFile = "rental2/calendar/includes/synctz.inc.php";
  if (file_exists($configFile)) {
      require_once ($configFile);
	  require_once ($synctzFile);
  } else {
	  exit;
  }

  require_once ("rental2/calendar/classes/class.db.php");

  require_once ("rental2/calendar/classes/class.vault.php");
  Vault::set('Database', new Database(DB_SERVER, DB_USER, DB_PASS, DB_DATABASE));
  $db = Vault::get("Database");
  $db->connect();
*/

//$XACTUAL=$_GET['ruta'];
?>
<head>
  <meta charset="UTF-8">
  <title>Gestion de Reservas </title>
     <link rel="stylesheet" href="assets/css/reservas2.css">
     <link href="https://fonts.googleapis.com/css?family=Didact+Gothic&display=swap" rel="stylesheet">
     
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

  <script>
  $( function() {
    $( "#datep1" ).datepicker();
  } );

   $( function() {
    $( "#datep2" ).datepicker();
  } );

  </script>

     
     
</head>


<body>

<?php


$XOBJPAG=new paginas;
$XPAGINA="'PAG_RES_GESTION'";
$XLENG="'ESP'";
$XCLASS="'001'";
$XRSPAG=$XOBJPAG->FncBuscarPagina($XLENG, $XPAGINA, $XCLASS);
$XI=0;
while($XROWPAG=$XOBJPAG->obtener_fila($XRSPAG)){//CREA EL ARREGLO PARA EL MENU
	$XLABEL[$XI]=utf8_encode($XROWPAG[0]);
	$XDISP[$XI]=$XROWPAG[1];
	$XAUT[$XI]=$XROWPAG[2];
	$XURL[$XI]=$XROWPAG[3];
	$XI++;
}
?>
<script type="text/javascript" src="assets/js/gestion_reservas3.js" ></script>
<script src="https://codepen.io/shshaw/pen/QmZYMG.js"></script>
<!-- <input type="radio" name="cice" id="nav-1" checked> -->
<div id="app">
<!-- Generated by IcoMoon.io -->
 <header>
   <nav>
    <div class="logo">
       <a href="index2.php"><img src="assets/images/logo-horos-transparente.fw.png" alt=""></a>
    </div>
    
      <div class="menu-a">
          <a href="buscar_reservas.php">Retornar</a>
      <a href="index2.php">Menu Principal</a>
      <a href="home.php">Disponibilidad de Habitaciones</a>
      </div>

    </nav>
  </header>
  <div class="ui-pages">
    <article id="buscar">
           	<?php
// Se buscan reservas creadas
             $fecha_actual = date("Y-m-d");
             $fecha_inicial = date("Y-m-d",strtotime($fecha_actual."- 4 month"));
             $fecha_final = date("Y-m-d",strtotime($fecha_actual."+ 4 month"));
             if (!isset($_POST['fechadesde']))
                  $fechadesde = $fecha_inicial;
             else
                     $fechadesde = $_POST['fechadesde'];
             if (!isset($_POST['fechahasta']))
                  $fechahasta = $fecha_final;
             else
                  $fechahasta = $_POST['fechahasta'];
        	echo'
            <form class="buscar" action="buscar_reservas.php" method="post">
                <h1>Buscar Reservas </h1>
                <div class="buscar-reserva">
                    <div class="rango">
                    <div><label> Numero de Reserva</label>
               	  		<input type="text" id="TxtReserva" name="idres" placeholder="'.$XLABEL[2].'" />
                    </div>
                    <div><label>Nombre del Cliente</label>
                        <input type="text" id="TxtComienza" name="guest" placeholder="'.$XLABEL[3].'" />
                    </div>
                </div>
                <div class="rango">
                    <div>
                        <label> Desde</label>
                        <input type="text" name="fechadesde" id="datep1" step="1" value='.$fechadesde .'>
                    </div>
                    <div> '.
                        ' <label>Hasta</label>
                        <input type="text" name="fechahasta" id="datep2" step="1" value='. $fechahasta .'>
                    </div>
                </div> ';
                        $calnav = '';
                        $calnav = $calnav. '
                <div class="rango">
                    <div>
                        <label>'.$XLABEL[15].'</label>
                        <SELECT id="idstatus" name="idstatus">';
                            $XOBJRES1=new greservas;
                            $filtro = "";
                            $XRSRES1=$XOBJRES1->buscar_estadoreserva($filtro);
	                        $XESTADORES=$XOBJRES1->numero_filas($XRSRES1);
	                        $calnav = $calnav . '
                            <option value="%"> Todas </option>';
	                       while($XROWRES1=$XOBJRES1->obtener_fila($XRSRES1)){
       		               $calnav = $calnav . '
                           <option value="'.$XROWRES1[0].'">'.$XROWRES1[1].'</option>';		  }
                            $calnav = $calnav . '</select>';
                            $calnav = $calnav . '
                    </div>
                </div>
                </div> 
                <div  class="botones">
                        <input type="submit"  name="buscar" id="BtnBuscar" value="'.$XLABEL[4].'" />
                        <a id="BtnCHECKSINR" href="checkin.php">sin reserva</a>
                    </div> 
                <h1>Habitaciones</h1>
                <div class="habitaciones">
                    ';
                  
                    $XOBJRES=new greservas;
	               $XRSRES=$XOBJRES->buscar_hospedaje1();
	               $XNUMHAB=$XOBJRES->numero_filas($XRSRES);
	               while($XROWRES=$XOBJRES->obtener_fila($XRSRES)){

		             $calnav = $calnav;

                        $hab = $XROWRES[1];
                         $idhab = $XROWRES[0];
                        $calnav = $calnav.'
                        
                            <a href="buscar_reservas.php?idhab='.$idhab.'" > <i>'.$hab.'  </i></a>
                        ';

                        }
                        $calnav = $calnav;
                        echo $calnav;
                        echo '
        	        </div>
                    
     	      	   </div>
                </div>';
             echo ' <input type="hidden" name="fechadesde" value='.$fechadesde.'>';
              echo ' <input type="hidden" name="fechahasta" value='.$fechahasta.'>';
           echo ' </form>';
			?>
		
          	<div id="buscar">
          	    <table id="resultado" >
          	<?php
          	
          	if ( isset($_POST['buscar']))
          	{
          	 $idres=$_POST['idres'];
          	$guest= $_POST['guest'];
          	$postdesde = $_POST['fechadesde'];
            $posthasta = $_POST['fechahasta'];
          	$fechadesde= date("Y-m-d", strtotime($postdesde));
          	$fechahasta= date("Y-m-d",strtotime($posthasta));

          	$idstatus=$_POST['idstatus'];
          	if ( isset($_POST['idhab']))
          	$idhab=$_POST['idhab'];
          	else
               $idhab="";
          	}
          	else
           {
                $idres="";
          	$guest= "";
        //  	  $fechadesde = date("Y-m-d",strtotime($fecha_actual."- 4 month"));
          //   $fechahasta = date("Y-m-d",strtotime($fecha_actual."+ 4 month"));
            $fechadesde = date("Y-m-d",strtotime($fecha_actual."- 4 month"));
             $fechahasta = date("Y-m-d",strtotime($fecha_actual."+ 4 month"));

          	$idstatus="%";
          	if (isset($_GET["idhab"]))
          	$idhab=$_GET["idhab"];
          	else
          	$idhab="";
           }
          	$filtros = "cd.id like '%".$idres."%' and cd.guestname like '%".$guest."%' and cd.checkin >= '".$fechadesde ."' and cd.checkout <= '".
              $fechahasta."' and cd.status like '".$idstatus."' and cd.ppttypeid like '%".$idhab."%'";
           	$XOBJRES=new greservas;
			$XRSRES=$XOBJRES->buscar_reservas_calendar($filtros);
			
			 $TAMANO_PAGINA = 20;
             //paginacion inicio paginacion segun el numero de registros a desplegar
                //examino la página a mostrar y el inicio del registro a mostrar

                if (isset($_GET["pagina"]))
                   $pagina = $_GET["pagina"];
                if (!isset($pagina)) {
                   $inicio = 0;
                   $pagina = 1;
                }
                else {
                     $inicio = ($pagina - 1) * $TAMANO_PAGINA;
                }


			
		//	$num_total_registros = 20;
                $num_total_registros = $XOBJRES->numero_filas($XRSRES);


            $total_paginas = ceil($num_total_registros / $TAMANO_PAGINA);
            if (($TAMANO_PAGINA + $inicio) <= $num_total_registros)
               $tampag = $TAMANO_PAGINA + $inicio;
            else
               $tampag = $num_total_registros;
            //COMPRUEBO QUE EL VALOR DE LA PÁGINA SEA CORRECTO Y SI ES LA ULTIMA PÁGINA
            echo "<caption>";
            echo '<ul id="pagination-clean"> ';
            if ($total_paginas > 1) {
             if ($pagina != 1) {
                echo '<li class="previous">';
                $pagant = $pagina - 1;
                    echo "<a href='buscar_reservas.php?pagina=$pagant' >

                    <img src='assets/images/izq.png' border='0'></a></li>";
               }
               for ($i=1;$i<=$total_paginas;$i++) {
                 if ($pagina == $i)
                    //si muestro el índice de la página actual, no coloco enlace
                     echo '<li class="active">'.$pagina.'</li>';
                 else
                  //si el índice no corresponde con la página mostrada actualmente,
                  //coloco el enlace para ir a esa página
                echo "<li> <a href='buscar_reservas.php?pagina=$i'".">".$i."</a></li>";
            }
            if ($pagina != $total_paginas)  {
               $pagnext = $pagina + 1;
                echo '<li class="next">';
                 echo "<a href='buscar_reservas.php?pagina=$pagnext'><img src='assets/images/der.png'></a></li>";
              }
            }
            echo "</ul></caption>";
                 $XNUMFILA = 0;
            	echo'<tr >
            	<td class="tituT" align="center" > # Reserva </td>
       	       	<td class="tituT" align="center" > # Habitacion </td>
             	<td class="tituT" align="center" > Cliente/Huesped </td>
   	           	<td class="tituT" align="center" > Estado Reserva </td>
           	 	<td class="tituT" align="center" > Checkin </td>
           	 	<td class="tituT" align="center" > Checkout </td>
               	<td class="tituT" align="center" > Fecha Reserva </td>

           	</tr>';

            $xi = $inicio;
             while($XROWRES=$XOBJRES->obtener_fila($XRSRES)){
            if ($xi < $tampag) {
            //   if ($XNUMFILA%2==0)
                   //      $color = "#ffcc33"; //si el resto de la divisi�n es 0 pongo un color
                   $color = $XROWRES[9];
             //  else
      	       //          $color = "#33658a";
             //	$XCODIGO=retornar_codigo(10,$XROWRES[0]);
				$XCODIGO="'".$XROWRES[0]."'";
				$statusid = "'".$XROWRES[4]."'";
				$numhab = "'".$XROWRES[2]."'";
				echo'<tr style="background-color:'.$color.'">
    	        	<td class="Txtmenu"><a onclick="PrcEncontrarReserva('.$XCODIGO.','.$statusid.','.$numhab.')" style="cursor:pointer">
						'.$XROWRES[0].'
					</td>
        	    	<td class="Txtmenu"><a onclick="PrcEncontrarReserva('.$XCODIGO.','.$statusid.','.$numhab.')" style="cursor:pointer">
						'.$XROWRES[1].' '.$XROWRES[2].'</a>
					</td>
  	 	            	 <td class="Txtmenu">'.$XROWRES[3].'</td>
    	   	       	<td class="Txtmenu">'.$XROWRES[4].' '.$XROWRES[8].'</td>
    	   	       	      	 <td class="Txtmenu">'.$XROWRES[5].'</td>
    	   	       	<td class="Txtmenu">'.$XROWRES[6].'</td>
                     	<td class="Txtmenu">'.$XROWRES[7].'</td><td>';
                echo '<a class="checkin-img" onclick="PrcEncontrarReserva('.$XCODIGO.','.$statusid.','.$numhab.')" style="cursor:pointer"><img src="assets/images/checkin.png" alt=""></a></td>
        	   	</tr>';
        	   	$XNUMFILA++;
        	   	$xi++;
              	}
			}

// finaliza busqueda de reservas creadas
			?>
      	</table><img src="" alt="">
          	</div>
        
      </article>

  </div>
</div>
     <script  src="js/indexpag.js"></script>
</body>
