<?php
include_once 'classes/paginas.class.php';
include_once 'classes/greservas.class.php';
include_once 'assets/funciones.php';
date_default_timezone_set("America/Bogota");

?>
<head>
  <meta charset="UTF-8">
  <title>Habitaciones Bloqueadas</title>
     <link rel="stylesheet" href="assets/css/reservas2.css">
     <link href="https://fonts.googleapis.com/css?family=Didact+Gothic&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

     
     
</head>


<body>

<script type="text/javascript" src="assets/js/gestion_reservas3.js" ></script>
<script src="https://codepen.io/shshaw/pen/QmZYMG.js"></script>
<!-- <input type="radio" name="cice" id="nav-1" checked> -->
<div id="app">
<!-- Generated by IcoMoon.io -->
 <header>
   <nav>
    <div class="logo">
       <a href="index2.php"><img src="assets/images/logo-horos-transparente.fw.png" alt=""></a>
    </div>
    
      <div class="menu-a">
          <a href="buscar_reservas.php">Retornar</a>
      <a href="index2.php">Menu Principal</a>
      <a href="home.php">Disponibilidad de Habitaciones</a>
        </div>


    </nav>
  </header>

  <?php
  
  // Si presiono guardar busco el id de la habitacion y la habilito
  if (isset($_POST["guardar"]))
  {
    	$XOBJRES=new greservas;
    if (isset($_POST["numerofilas"]))
       $numerofilas = $_POST["numerofilas"];
    else
       $numerofilas = 0;
    for ($i=0;$i < $numerofilas;$i++)
    {
       if (isset($_POST["idhab"][$i]))
         $idhab = $_POST["idhab"][$i];
       else
         $idhab = "";
         if (isset($_POST['seleccion'][$i]) )
             if ($_POST['seleccion'][$i] != null)
             {
                   // voy a actualizar habitacion estado
                   $XACTHAB=$XOBJRES->actualiza_habestado($idhab);

             }
      }
    
  }
  
  
  
  // busco numero de habitaciones ocupadas
               $hoy = date('Y-m-d');
     	       $XOBJRES=new greservas;
               $XNUMOCU=$XOBJRES->buscar_ocupadas($hoy);
               $XOCUP = $XOBJRES->obtener_fila($XNUMOCU);
               $OCUPADA = $XOCUP[0];
               echo '
                 <div class="ocupado">
                 <span>habitaciones ocupadas</span> <br>
                 <span>'. $OCUPADA. ' de 42</span>
                 </div>';
?>

  <div class="ui-pages">
    <article id="buscar">
           	<?php
           	
       	echo'
            <form class="buscar" action="hbloqueada.php" method="post">
                <h1>Habitaciones Bloqueadas </h1>

                    ';



           	$XOBJRES=new greservas;

			$XRSRES=$XOBJRES->buscar_hbloqueada();
            $XNUMFILA = 0;
             echo '    	<table id="resultado" >  ';
            	echo'<tr >
           		<td class="tituT" align="center" > Id hab </td>
            	<td class="tituT" align="center" > Selec </td>
            	<td class="tituT" align="center" > # Hab </td>
                <td class="tituT" align="center" > Fecha Bloqueo </td>
                <td class="tituT" align="center" > Descripcion </td>
           	 	<td class="tituT" align="center" > Max Ocupacion </td>
   	 	 	 	<td class="tituT" align="center" > Imagen </td>
 		       </tr>';

            $i = 0;
            $numerofilas = 0;
            while($XROWRES=$XOBJRES->obtener_fila($XRSRES)){
           		$numhab = $XROWRES[1];
				$fechacheq = $XROWRES[3];
				$nombre = $XROWRES[5];
               	$maxocupacion = $XROWRES[4];
              	$imagen = $XROWRES[6];
              	$idhab = $XROWRES[0];
        		echo'<tr>
        		   <td > <input type="text" class="Txtmenu" name="idhab['.$i.']" value="'.$idhab.'" readonly> </td>
        	      <td > <input type="checkbox" name="seleccion['.$i.']" value="0" > </td>
               	<td >' . $numhab.'</td>
        	    	<td > '.$fechacheq.'</td>
            	    <td >'.$nombre.'</td>
    	   	       	<td >'.$maxocupacion.'</td>
    	   	       	<td class="checkin-img1"><img src="'.$imagen.'"  alt=""></img></td> ';
                echo ' </tr> ';
                $i++;
                $numerofilas++;
           	}


       echo '<input type="hidden" name="numerofilas" value='.$numerofilas.'>';
      echo '	</table><img src="" alt=""> ';
      echo '<div style="position: relative;">
        <div  class="botones">
        <input type="submit"  name="guardar" id="BtnBuscar" value="HABILITAR" />
        </div>

          	</div>
          	
          	          </form>';

?>
        
      </article>

  </div>

</div>
</body>
